# Generated by Django 5.0.14 on 2026-07-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
