# Generated by Django 5.2.9 on 2026-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIOS', '0002_alter_envio_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='ciudad_destino',
            field=models.CharField(default='Quito', help_text='Ciudad de destino', max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='correo_destinatario',
            field=models.EmailField(blank=True, help_text='Correo electrónico del destinatario', max_length=254),
        ),
        migrations.AddField(
            model_name='envio',
            name='hora_estimada_llegada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora estimada de llegada (ETA)', null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='oficina',
            field=models.CharField(default='Oficina Central Latacunga', help_text='Oficina de recepción/procesamiento', max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen',
            field=models.CharField(default='Latacunga', help_text='Ciudad u oficina de origen', max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='transporte',
            field=models.CharField(default='Camión Exprés 01', help_text='Unidad de transporte asignada', max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='ubicacion_actual',
            field=models.CharField(default='Centro de Acopio Latacunga', help_text='Ubicación actual de la encomienda', max_length=200),
        ),
    ]
