# Generated by Django 5.2.15 on 2026-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIOS', '0003_envio_ciudad_destino_envio_correo_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Código QR de rastreo', null=True, upload_to='qr_codes/'),
        ),
    ]
