# Generated by Django 5.2.15 on 2026-07-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIOS', '0004_envio_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nombre_completo',
            field=models.CharField(blank=True, help_text='Nombre completo del usuario (para clientes)', max_length=200),
        ),
    ]
