# Generated by Django 5.2.15 on 2026-07-22 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIOS', '0005_add_nombre_completo_to_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-fecha_recepcion']},
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_recepcion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de recepción del paquete (se registra automáticamente)'),
        ),
    ]
